In [ ]:
from google.colab import drive
drive.mount('/content/drive')

FOLDERNAME = 'OSSProject2'
assert FOLDERNAME is not None, "[!] Enter the foldername."

import sys
sys.path.append('/content/drive/MyDrive/{}'.format(FOLDERNAME))
%cd /content/drive/MyDrive/$FOLDERNAME
%ls

In [ ]:
#데이터 설치
!pip install matplotlib
!pip install scikit-learn
!pip install pandas
!pip install numpy

In [2]:
import pandas as pd
import numpy as np

In [3]:
ratings_data = pd.read_csv('ratings.dat', sep='::', header=None, names=['user_id', 'movie_id', 'rating', 'timestamp'],engine='python')

In [4]:
ratings_data.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [5]:
user_item_matrix = ratings_data.pivot_table('rating', index='user_id', columns='movie_id')

In [6]:
user_item_matrix.head()

movie_id,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
ids = list(range(1, 3953))

In [8]:
user_item_matrix = user_item_matrix.reindex(columns=ids)

In [9]:
user_item_matrix = user_item_matrix.fillna(0)

In [10]:
user_item_matrix.head()

movie_id,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 3, random_state = 42)
kmeans.fit(user_item_matrix)

KMeans(n_clusters=3, random_state=42)

In [12]:
labels = kmeans.predict(user_item_matrix)

In [13]:
labels

array([1, 2, 1, ..., 1, 1, 2], dtype=int32)

In [14]:
# 각 유저의 클러스터 레이블 확인
user_groups = pd.DataFrame({'user_id': ratings_data['user_id'].unique(), 'group': labels})
user_groups.head()

   user_id  group
0        1      1
1        2      2
2        3      1
3        4      1
4        5      1

In [59]:
user_item_matrix = user_item_matrix.astype(np.uint8)
user_item_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
user_id,,,,,,,,,,,,,,,,,,,,,
1,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6036,0,0,0,2,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6037,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6038,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6039,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6040,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
def get_user_item_matrix_by_group(user_item_matrix, user_groups, group_id):
    group_users = user_groups[user_groups['group'] == group_id]['user_id']
    group_matrix = user_item_matrix.loc[group_users]
    return group_matrix
get_user_item_matrix_by_group(user_item_matrix, user_groups, 2)

movie_id,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
user_id,,,,,,,,,,,,,,,,,,,,,
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,4,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,4,2,0,0,0,0,0,0,0,5,...,0,0,0,0,0,0,0,0,0,0
19,5,0,0,0,0,0,0,0,0,5,...,0,0,0,0,0,4,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6025,5,0,3,3,0,0,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6030,0,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6035,4,0,1,2,1,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6037,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6040,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
def AU(group_matrix):
    return np.sum(group_matrix, axis=0)

In [17]:
def Avg(group_matrix):
    return np.mean(group_matrix, axis=0)

In [18]:
def SC(group_matrix):
    return group_matrix[group_matrix > 0].count(axis=0)

In [19]:
def AV(group_matrix):
    return group_matrix[group_matrix >=4].count(axis=0)

In [20]:
def BC(group_matrix):
    res = pd.DataFrame(columns = group_matrix.columns)
    for i in group_matrix.index:
        temp = group_matrix.loc[i]
        temp = temp.rank(method='average') - 1
        res.loc[i] = temp
    return res.sum(axis = 0)

In [21]:
def BC_Optimized(group_matrix):
    return group_matrix.rank(method='average', axis=1).sum(axis=0) - group_matrix.shape[0]

In [22]:
def CR(group_matrix):
    n = 100
    res = pd.DataFrame(index=group_matrix.columns[:n], columns=group_matrix.columns[:n], dtype=float)
    for i in group_matrix.columns[:n]:
        for j in group_matrix.columns[:n]:
            if i == j:
                continue
            g = (group_matrix[i] > group_matrix[j]).value_counts().get(True, 0)
            l = (group_matrix[i] < group_matrix[j]).value_counts().get(True, 0)
            if g > l:
                res.at[i,j] = 1
            elif g == l:
                res.at[i,j] = 0
            else:
                res.at[i,j] = -1
    return res.sum(axis=0)

In [23]:
def CR_Optimized(group_matrix):
    nparr = group_matrix.T.values
    n = 1000
    res = np.zeros((n,n))
    idx_upper = np.triu_indices(n, k = 1)
    for i in range(n):
        for j in range(i+1, n):
            res[i,j] = (nparr[i] > nparr[j]).sum()
            res[j,i] = (nparr[i] < nparr[j]).sum()
    # 
    return pd.Series(  np.sign(res - res.T).sum(axis = 0), index = group_matrix.columns[:n])

In [40]:
def CR_Optimized2(group_matrix):
    n = len(group_matrix.columns)
    # n = 1000
    nparr = group_matrix.T.values
    res = np.zeros((n,n))
    idx_upper = np.triu_indices(n, k=1)
    res[idx_upper] = (nparr[idx_upper[0]] > nparr[idx_upper[1]]).sum(axis = 1)
    res.T[idx_upper] = (nparr[idx_upper[0]] < nparr[idx_upper[1]]).sum(axis = 1)
    result = pd.Series(  np.sign(res - res.T).sum(axis = 0), index = group_matrix.columns[:n])
    del nparr, res, idx_upper
    return result

In [51]:
def CR_Optimized2_Sub(group_matrix, res, idx_upper):
    n = len(group_matrix.columns)
    res[idx_upper] += (group_matrix.T.values[idx_upper[0]] > group_matrix.T.values[idx_upper[1]]).sum(axis = 1)
    res.T[idx_upper] += (group_matrix.T.values[idx_upper[0]] < group_matrix.T.values[idx_upper[1]]).sum(axis = 1)
    del idx_upper

In [71]:
def CR_Optimized2_Chunk(group_matrix):
    n = len(group_matrix.columns)
    idx_upper = np.triu_indices(n, k=1)
    res = np.zeros((n,n), dtype = np.int16)
    total = len(group_matrix.index)
    chunk_size = 1000
    for start in range(0, total, chunk_size):
        end = min(start + chunk_size, total)
        # print(start, end)
        subgroup = group_matrix.iloc[start:end, :]
        CR_Optimized2_Sub(subgroup, res, idx_upper)
        del subgroup
        
    result = pd.Series(  np.sign(res - res.T).sum(axis = 0), index = group_matrix.columns)
    del res
    return result

In [28]:
def printList(series):
    for i, v in enumerate(series):
        print(f'{i+1}. {v}')

In [72]:
for groupnumber in range(3):
  group = get_user_item_matrix_by_group(user_item_matrix, user_groups, groupnumber)
  additiveUtilitarian = AU(group)
  average = Avg(group)
  simpleCount = SC(group)
  approvalVoting = AV(group)
  bordaCount = BC_Optimized(group)
  copelandRule = CR_Optimized2_Chunk(group)
  print(f"top 10 mvoies of group {groupnumber} using Additive Utilitarian")
  printList(additiveUtilitarian.nlargest(10).index)
  print(f"top 10 mvoies of group {groupnumber} using Average")
  printList(average.nlargest(10).index)
  print(f"top 10 mvoies of group {groupnumber} using Simple Count")
  printList(simpleCount.nlargest(10).index)
  print(f"top 10 mvoies of group {groupnumber} using Approval Voting")
  printList(approvalVoting.nlargest(10).index)
  print(f"top 10 mvoies of group {groupnumber} using Borda Count")
  printList(bordaCount.nlargest(10).index)
  print(f"top 10 mvoies of group {groupnumber} using Copeland Rule")
  printList(copelandRule.nlargest(10).index)

top 10 mvoies of group 0 using Additive Utilitarian
1. 260
2. 1196
3. 1198
4. 1270
5. 608
6. 593
7. 296
8. 858
9. 2571
10. 1197
top 10 mvoies of group 0 using Average
1. 260
2. 1196
3. 1198
4. 1270
5. 608
6. 593
7. 296
8. 858
9. 2571
10. 1197
top 10 mvoies of group 0 using Simple Count
1. 1196
2. 260
3. 1270
4. 1580
5. 1210
6. 1097
7. 2716
8. 1198
9. 589
10. 480
top 10 mvoies of group 0 using Approval Voting
1. 260
2. 1196
3. 1198
4. 593
5. 858
6. 608
7. 1270
8. 2858
9. 296
10. 318
top 10 mvoies of group 0 using Borda Count
1. 1196
2. 260
3. 1270
4. 1198
5. 1210
6. 608
7. 1097
8. 296
9. 2716
10. 593
top 10 mvoies of group 0 using Copeland Rule
1. 51
2. 53
3. 91
4. 109
5. 115
6. 127
7. 130
8. 133
9. 134
10. 139
top 10 mvoies of group 1 using Additive Utilitarian
1. 2858
2. 260
3. 1210
4. 2028
5. 1196
6. 2762
7. 593
8. 527
9. 2396
10. 110
top 10 mvoies of group 1 using Average
1. 2858
2. 260
3. 1210
4. 2028
5. 1196
6. 2762
7. 593
8. 527
9. 2396
10. 110
top 10 mvoies of group 1 using Simple Count
1. 2858
2. 260
3. 1210
4. 1196
5. 2028
6. 593
7. 480
8. 2762
9. 2396
10. 2997
top 10 mvoies of group 1 using Approval Voting
1. 2858
2. 260
3. 2028
4. 2762
5. 593
6. 1196
7. 527
8. 1210
9. 2396
10. 608
top 10 mvoies of group 1 using Borda Count
1. 2858
2. 260
3. 1210
4. 1196
5. 2028
6. 593
7. 2762
8. 480
9. 2396
10. 2997
top 10 mvoies of group 1 using Copeland Rule
1. 51
2. 91
3. 98
4. 109
5. 115
6. 136
7. 138
8. 139
9. 142
10. 143
top 10 mvoies of group 2 using Additive Utilitarian
1. 1196
2. 260
3. 2571
4. 1198
5. 2858
6. 1210
7. 2028
8. 589
9. 593
10. 1270
top 10 mvoies of group 2 using Average
1. 1196
2. 260
3. 2571
4. 1198
5. 2858
6. 1210
7. 2028
8. 589
9. 593
10. 1270
top 10 mvoies of group 2 using Simple Count
1. 1196
2. 260
3. 2571
4. 1210
5. 589
6. 2858
7. 1580
8. 480
9. 1270
10. 1198
top 10 mvoies of group 2 using Approval Voting
1. 1196
2. 260
3. 1198
4. 2571
5. 2858
6. 2028
7. 593
8. 589
9. 1210
10. 2762
top 10 mvoies of group 2 using Borda Count
1. 1196
2. 260
3. 2571
4. 1210
5. 2858
6. 589
7. 1198
8. 1580
9. 480
10. 2028
top 10 mvoies of group 2 using Copeland Rule
1. 51
2. 67
3. 91
4. 109
5. 115
6. 120
7. 127
8. 133
9. 143
10. 192

In [63]:
group_matrix = get_user_item_matrix_by_group(user_item_matrix, user_groups, 0)
group_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
user_id,,,,,,,,,,,,,,,,,,,,,
10,5,5,0,0,0,0,4,0,0,0,...,0,0,0,0,0,4,0,0,0,0
36,5,0,0,0,0,5,4,0,0,4,...,0,0,0,0,0,0,0,0,0,5
48,4,3,0,0,3,4,4,0,0,4,...,0,0,0,0,0,3,0,0,0,0
53,0,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,4,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5972,4,0,3,0,0,0,3,0,0,0,...,0,0,0,0,0,2,0,0,0,0
5996,5,3,0,0,4,0,5,0,0,4,...,0,0,0,2,0,3,0,0,0,0
6000,3,3,3,0,3,0,4,3,0,3,...,0,0,0,0,0,0,0,0,0,0
6016,4,0,2,0,0,0,3,0,0,4,...,0,0,0,0,0,0,0,0,0,0
6036,0,0,0,2,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [135]:
# %%timeit
copelandRule = CR(group_matrix)
copelandRule

movie_id
1     -97.0
2     -69.0
3     -55.0
4     -10.0
5     -37.0
       ...
96     78.0
97     56.0
98     85.0
99     56.0
100   -15.0
Length: 100, dtype: float64

In [67]:
%%timeit
copelandRule = CR(group_matrix)
copelandRule

2.69 s ± 33.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [145]:
# %%timeit
copelandRule = CR_Optimized(group_matrix)
copelandRule

movie_id
1      -977.0
2      -801.0
3      -652.0
4      -234.0
5      -508.0
        ...
996    -463.0
997     361.0
998      -9.0
999    -575.0
1000    436.0
Length: 1000, dtype: float64

In [146]:
%%timeit
copelandRule = CR_Optimized(group_matrix)
copelandRule

2.58 s ± 88.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [67]:
copelandRule = CR_Optimized2(group_matrix)
copelandRule

movie_id
1      -3899.0
2      -3062.0
3      -2401.0
4       -793.0
5      -1904.0
         ...
3948   -2829.0
3949   -1890.0
3950     672.0
3951    1900.0
3952   -1784.0
Length: 3952, dtype: float64

In [70]:
%%timeit
copelandRule = CR_Optimized2(group_matrix)
copelandRule

6.85 s ± 376 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [66]:
copelandRule = CR_Optimized2_Chunk(group_matrix)
copelandRule

movie_id
1      -3899
2      -3062
3      -2401
4       -793
5      -1904
        ...
3948   -2829
3949   -1890
3950     672
3951    1900
3952   -1784
Length: 3952, dtype: int64

In [69]:
%%timeit
copelandRule = CR_Optimized2_Chunk(group_matrix)
copelandRule

10.6 s ± 305 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [139]:
copelandRule = CR_Optimized3(group_matrix)
copelandRule

movie_id
1      -977.0
2      -801.0
3      -652.0
4      -234.0
5      -508.0
        ...
996    -463.0
997     361.0
998      -9.0
999    -575.0
1000    436.0
Length: 1000, dtype: float64

In [140]:
%%timeit
copelandRule = CR_Optimized3(group_matrix)
copelandRule

2.61 s ± 50.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [51]:
np.sign(copelandRule).sum(axis = 0)

array([-977., -801., -652., -234., -508., -897., -701.,  176.,  -90.,
       -861., -893., -218.,   85., -356., -181., -865., -796., -354.,
       -581., -253., -933., -686., -227., -633., -873., -101.,   90.,
       -120., -617.,  163., -257., -957.,  681., -953.,  113., -877.,
        644.,  387., -936.,  436., -400., -337., -154., -570., -803.,
       -197., -943., -525.,  452., -985.,  889., -732.,  889.,  338.,
        328.,  644., -124., -626.,  681., -507.,   50., -747.,  -73.,
         37., -214.,   98.,  642.,  225., -522., -829.,  -69.,    9.,
       -170.,   34.,  566., -212.,  310.,   86., -115.,  358., -319.,
        154.,  451.,  517., -257., -319.,   99., -347., -465.,  738.,
        889.,  -88., -116., -393., -777.,  550.,  283.,  647.,  285.,
       -260., -447.,   46.,  300., -795., -581.,  616., -346.,  640.,
        889., -983., -946., -782.,  208.,  595.,  889.,  301.,   18.,
        103.,  476.,  677.,  404., -391.,  -41.,  542., -584.,  127.,
        889.,  613.,  564.,  889.,  493.,  -78.,  889.,  889., -273.,
        616.,  590.,  728.,  889., -143., -849.,  889.,  889., -597.,
       -563.,  516., -355.,  340.,  297., -939., -779.,  121., -798.,
       -206.,   63.,  156., -358., -438., -250., -668., -859., -706.,
       -763., -568., -872.,  148.,  642., -599.,  -33., -539.,  -43.,
       -588., -690.,  -27., -474., -331., -280.,  442.,  225., -716.,
        -20.,  256.,  347.,  253., -732., -379.,  -22., -321.,  537.,
        -11.,    2.,  737., -410., -453., -263., -712.,  499., -754.,
         52.,  490.,  284.,  405., -411., -351.,   27.,   54., -347.,
       -769.,  162.,  322.,  345.,  541.,  192.,  449., -192., -598.,
        166., -412.,  460.,  368.,  889., -517., -927., -653., -543.,
        889., -130.,  480., -192., -652., -827., -378., -343., -269.,
       -901., -567., -502.,  419., -160.,  311.,  276.,  227.,  563.,
        643.,  593., -772., -654., -207., -504.,  365.,  477., -637.,
       -847.,  274.,   78., -410., -159.,   45., -172., -999., -456.,
       -164.,  442.,  737., -742., -755., -180.,  213.,  130.,  154.,
        129., -651., -479.,  427.,  -68., -398., -241.,  236.,  250.,
       -511., -428., -492.,  591.,  889.,  889.,  737.,  482., -837.,
       -263., -113.,  252., -826., -907.,  320.,  367., -995.,  351.,
        487.,  -67., -873.,  340.,  112., -687.,  384., -169., -432.,
       -432., -291.,  531.,  889.,  738., -110.,  364., -397., -263.,
       -880., -744., -991., -518.,  319.,  255., -450.,  889.,  396.,
        166.,  210., -528., -103., -838., -225.,  480., -136., -730.,
        -32.,  239.,  458., -853., -364., -790.,  -35.,  455., -720.,
        404., -832., -660., -232.,  252., -701., -897., -718., -409.,
        -77., -843.,   75., -510., -979., -921., -153.,  405., -182.,
       -492., -393.,  300., -925.,   12., -325., -905., -860.,  109.,
       -628., -481., -697., -520., -330.,  443., -610., -953., -141.,
       -658., -945., -381., -524., -509.,  216.,  616.,  312.,  -89.,
        -52.,  503.,  109.,  339.,  401.,   -7.,  511.,  889.,  737.,
        642.,  737.,  889.,  889.,  889.,  889.,  889.,  889., -179.,
        643., -255.,  112.,  253., -724.,  454., -524., -489., -110.,
       -383.,  -40., -302.,  291., -264., -596.,   24.,   38., -450.,
        -31.,   69., -374., -308., -532., -394.,  323., -702., -647.,
        181., -797., -723., -326.,   38., -220.,  889., -915., -828.,
       -765.,  355.,    7.,  -87., -289.,  296., -490.,  122., -495.,
        -41.,  313.,   66., -873., -449.,  -44., -971.,  -22., -257.,
        177.,  132.,  416.,  222., -400.,    1., -753.,  228., -571.,
        181.,  273., -838.,  201., -265., -923., -576.,  411., -384.,
        275., -220., -969., -550., -302.,  103.,  407., -725.,   97.,
         89.,  207.,  -69., -410., -450., -558., -400., -697.,  291.,
        395., -821.,  267.,  133., -856.,   41., -201.,  509., -279.,
         -3.,  -93., -623., -827., -795.,  213., -259., -228.,   35.,
       -652., -659., -510., -660., -336., -276., -656., -268.,   -1.,
        -78., -670.,  391.,  596., -987.,   73., -855.,  728., -459.,
       -620., -433., -442., -581.,   78., -422., -587., -889., -312.,
       -975., -429., -838., -184.,  889., -458., -141., -255., -104.,
       -290., -896., -741., -791.,  524., -838.,  -36.,  889.,    5.,
        734.,  644.,  515., -745.,  505.,  212.,  160.,  545.,  561.,
        399., -106.,  484.,  420.,  735.,  644., -306.,  -78.,  889.,
        205.,  737.,  889.,  138., -159.,  737.,  562.,  728., -684.,
       -815., -915., -929., -981., -959.,  737., -961., -993., -871.,
       -909., -774., -911.,  642., -537.,  256.,  889.,  392.,  141.,
        889., -373.,   65.,  741., -989.,  145., -751., -154.,  117.,
        117.,  547.,  412., -507.,  509.,  693.,  315.,  889.,  277.,
        889.,  737.,  889.,  889.,  465., -207., -765.,  889.,  573.,
        175.,  569.,  538.,  678.,   15.,  889., -204.,  458.,   18.,
        -10.,  889.,  889.,  889.,  889.,  590.,  889., -749., -913.,
        590.,   16.,  889.,  589., -725.,  889.,  889.,  215.,  889.,
        889.,  346.,  750., -681., -271., -509.,  572.,  471.,  721.,
        303.,  345.,  454.,  352., -590.,  889., -668., -607.,  889.,
        889.,  889., -377.,  741.,  206.,  536.,  680.,  889.,  889.,
        501.,  889.,  681., -202.,  889.,  889.,  -56.,    2.,  889.,
       -187., -146.,  737.,  -40.,  676.,  889., -209.,  728.,  382.,
        539.,  304.,  317.,  678., -489., -815., -177.,  177.,  174.,
        741.,  889., -175.,  209.,  401.,  737.,  396., -521., -580.,
        889.,  584.,  889., -659., -100.,  556.,  889., -359.,  737.,
        889.,  250.,  645., -925.,  737.,   75., -864., -405.,  889.,
        889.,  889., -413., -227., -142.,  676., -683.,  347.,  115.,
       -624.,  741., -963.,  504.,  889.,  425.,  587.,  611.,  889.,
        678.,  889.,  457.,  437., -229., -572.,  741.,  107., -331.,
       -114.,  394.,  889.,  512.,  889.,  618.,  889.,  889.,  737.,
        595.,  736.,  889., -876.,  257., -935.,  -73., -271., -611.,
       -675., -810., -717.,  677., -813.,  889.,  889.,  889.,  889.,
        737.,  889.,  889.,  675.,  889., -430., -580., -787.,  -42.,
       -721.,  121., -368., -655.,  138.,  616.,  337.,  -53.,  -22.,
        618.,  889.,  169.,  737.,  643.,  889.,  889., -411.,  889.,
        728.,  737.,  889.,  737.,  523.,  889.,  889.,  741.,  380.,
       -125., -556.,  536., -811.,   -6.,  678.,  -82., -455., -280.,
       -630., -123.,  195.,  502., -130.,  737.,  675.,  889.,  359.,
        616., -290., -670.,  559., -139., -774.,  737.,  642.,  889.,
        889.,  889., -997.,  889.,  593., -474.,  358.,  676.,  592.,
        737., -805.,  458.,  889.,  243.,  278.,  889.,  889.,  889.,
        580.,  187.,  508.,  405.,  889., -458., -533.,   80.,   80.,
        889.,  741.,  323.,  -37.,  889.,  291.,  889.,  889.,  -93.,
       -144.,   54.,  889.,  889.,  397.,  -71., -704., -819., -515.,
       -307., -777., -905., -943., -582., -306.,   42., -945., -693.,
       -875., -531., -967., -883., -792., -601., -659.,   44., -233.,
       -973., -891., -533., -697., -953., -965.,  684., -625.,   17.,
       -589.,   41., -646., -359., -224., -700., -539.,  127.,  -58.,
        230., -297.,  539., -523.,  -72., -373., -237., -157., -334.,
       -221., -165., -257., -308., -461., -568., -473., -929., -738.,
       -628.,  454.,  386.,  559.,  195.,  484.,  414.,  502.,  178.,
        213., -448.,  639.,  524., -766., -884.,  226., -531.,  645.,
         96.,  583.,  889.,  191.,  889.,   62.,  889.,  618.,  737.,
         75.,  889.,  242.,  678., -329.,  252.,   -2.,  889.,  170.,
       -346.,  381.,  560., -711.,  889., -463.,  361.,   -9., -575.,
        436.])